heat_template_version: 2014-10-16


description: >
  A template which provides a fake loadbalancer definition used in situation when HA is not required.


parameters:

  key_name:
    description: >
      A pre-submitted SSH key to access the VM hosts
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    description: >
      Select a base image to use for the infrastructure server
    type: string
    constraints:
    - custom_constraint: glance.image

  flavor:
    description: >
      Define the hardware characteristics for the VMs: CPU, Memory, base disk
    type: string
    constraints:
    - custom_constraint: nova.flavor

  hostname:
    description: >
      The load balancer hostname portion of the FQDN
    type: string

  domain_name:
    description: >
      All VMs will be placed in this domain
    type: string

  rhn_username:
    description: >
      A valid user with entitlements to RHEL and OpenShift software repos
    type: string

  rhn_password:
    description: >
      The password for the RHN user
    type: string
    hidden: true

  rhn_pool:
    description: >
      A subscription pool containing the RHEL and OpenShift software repos
      OPTIONAL
    type: string
    hidden: true

  ssh_user:
    description: >
      The user for SSH access to the VM hosts
    type: string

  external_network:
    description: >
      The user for SSH access to the VM hosts
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_network:
    description: >
      The name or ID of the internal network
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  ansible_public_key:
    description: >
      The SSH public key that Ansible will use to access master and node hosts
      This will be placed on each VM host in /root/.ssh/authorized_keys
    type: string

  dns_ip:
    description: IP address of the DNS server
    type: string

outputs:
  floating_ip:
    description: Dummy floating IP for non-existant load balancer
    value: ''

  console_url:
    description: Dummy URL for non-existant load balancer web UI
    value: ''

  api_url:
    description: Dummy URL for non-existant load balancer REST API
    value: ''
