heat_template_version: 2014-10-16


description: >
  OpenShift Node


parameters:

  key_name:
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    type: string
    constraints:
    - custom_constraint: glance.image

  flavor:
    type: string
    constraints:
    - custom_constraint: nova.flavor

  external_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  management_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  management_subnet:
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  container_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  container_subnet:
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  dns_ip:
    type: string
    description: IP address of the DNS server

  rhn_username:
    type: string

  rhn_password:
    type: string
    hidden: true

  rhn_pool:
    type: string
    hidden: true

  ssh_user:
    type: string


resources:

  host:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      networks:
      - port: {get_resource: management_port}
      - port: {get_resource: container_port}
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: init}

  container_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: container_network}
      fixed_ips:
      - subnet: {get_param: container_subnet}
      replacement_policy: AUTO
      value_specs:
        port_security_enabled: false

  init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: included_files}
      - config: {get_resource: rhn_register}
      - config: {get_resource: node_boot}

  included_files:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /etc/sysconfig/network-scripts/ifcfg-eth1
          content:
            str_replace:
              params:
                $IPADDR: {get_attr: [container_port, fixed_ips, 0, ip_address]}
                $HWADDR: {get_attr: [container_port, mac_address]}
              template: {get_file: fragments/ifcfg-eth1}

  rhn_register:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $RHN_USERNAME: {get_param: rhn_username}
            $RHN_PASSWORD: {get_param: rhn_password}
            $POOL_ID: {get_param: rhn_pool}
          template: {get_file: fragments/rhn-register.sh}

  node_boot:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: fragments/node-boot.sh}

  management_port:
    type: OS::Neutron::Port
    properties:
      security_groups:
      - {get_resource: security_group}
      network: {get_param: management_network}
      fixed_ips:
      - subnet: {get_param: management_subnet}
      replacement_policy: AUTO

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
      - protocol: icmp
      # Just open everything for now:
      - protocol: tcp
        port_range_min: 0
        port_range_max: 65535
      - protocol: udp
        port_range_min: 0
        port_range_max: 65535

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      port_id: {get_resource: management_port}


outputs:
  ip_address:
    description: IP address of the node
    value: {get_attr: [floating_ip, floating_ip_address]}
