heat_template_version: 2014-10-16


description: >
  Prepare an environment for deployment of OpenShift 3


parameters:

  ssh_key_name:
    type: string
    description: Name of the SSH keypair registered with Nova
    constraints:
    - custom_constraint: nova.keypair

  server_image:
    type: string
    description: Name or ID of the host image registered with Glance
    constraints:
    - custom_constraint: glance.image

  flavor:
    type: string
    description: The Nova flavor to use for the OpenShift nodes
    default: m1.medium
    constraints:
    - custom_constraint: nova.flavor

  external_network:
    type: string
    description: >
      The external network that provides floating IP addresses for the nodes
    constraints:
    - custom_constraint: neutron.network

  dns_nameserver:
    type: comma_delimited_list
    description: address of a dns nameserver reachable in your environment
    default: 8.8.8.8

  node_count:
    type: number
    description: >
      Numer of Nova servers to create.

  rhn_username:
    type: string
    description: >
      The username for registering the hosts with RHN. If empty, they will not
      be registered.
    default: ''

  rhn_password:
    type: string
    description: >
      The password for registering the hosts with RHN. If empty, they will not
      be registered.
    hidden: true
    default: ''

  rhn_pool:
    type: string
    description: >
      The pool to attach. Will use `subscription-manager attach --auto` if left
      blank.
    hidden: true
    default: ''

  container_network_cidr:
    type: string
    description: >
      The IP address range for the container network.
    default: 172.16.0.0/16


resources:

  management_network:
    type: OS::Neutron::Net

  management_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: 192.168.0.0/24
      network: {get_resource: management_network}
      dns_nameservers: {get_param: dns_nameserver}

  container_network:
    type: OS::Neutron::Net

  container_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: {get_param: container_network_cidr}
      network: {get_resource: container_network}
      dns_nameservers: {get_param: dns_nameserver}

  external_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_param: external_network}

  external_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: {get_resource: external_router}
      subnet: {get_resource: management_subnet}

  openshift_nodes:
    depends_on: external_router_interface
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: node_count}
      resource_def:
        type: node.yaml
        properties:
          image: {get_param: server_image}
          flavor: {get_param: flavor}
          key_name: {get_param: ssh_key_name}
          ssh_user: {get_param: ssh_user}
          external_network: {get_param: external_network}
          dns_ip: {get_attr: [dnsmasq_floating_ip, floating_ip_address]}
          fixed_network: {get_resource: fixed_network}
          fixed_subnet: {get_resource: fixed_subnet}
          container_network: {get_resource: container_network}
          container_subnet: {get_resource: container_subnet}
          container_security_group: {get_resource: container_security_group}
          rhn_username: {get_param: rhn_username}
          rhn_password: {get_param: rhn_password}
          rhn_pool: {get_param: rhn_pool}

outputs:
  servers:
    description: IP addresses of the Nova servers
    value: {get_attr: [openshift_nodes, outputs_list, ip_address]}
  inventory:
    description: Line-separated Floating IP addresses of the Nova servers
    value:
      list_join:
      - "\n"
      - {get_attr: [openshift_nodes, outputs_list, ip_address]}